---
# yamllint disable rule:line-length
exclude: (CMakeFiles|cmake_modules|docs|target)\/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-tabs
        exclude_types:
          - javascript
          - dtd
          - markdown
          - makefile
          - xml
          - css
          - svg
          - go
        exclude: binary|\.bin|go.mod$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-cyclo
        args: [-over=20]
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-staticcheck-mod
      - id: go-critic
      - id: go-vet-mod
      - id: go-mod-tidy
      - id: go-revive
