---
# yamllint disable rule:line-length
name: release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release GO binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: darwin
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v2

      - uses: wangyoucao577/go-release-action@v1.42
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.21.5"
          extra_files: LICENSE README.md

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: gherynos/vault-backend:${{ github.ref_name }}, gherynos/vault-backend:latest
